### ISSUE TITLE
Newbie Question - why downloading components first before uploading

### ISSUE THREAD

**Issue by tgruenert** [kubesphere/kubekey#1156]
Hi! 
First of all, i am totally new to kubesphere. I have managed to run it quite nice so the entry barrier for first time user seems to be low enough ;-). Thanks for your great work.
At my case i run kubekey from a local station where all my configuration files reside (managed and shared with git in my team). My connection can download much faster than upload.

If i do it this way i wounder that kubekey download some huge artefacts like docker just to upload them (slowly) than to every single node. The bigger the cluster is the longer it takes. 
Is there a good reason to do this this way? Or is there an option to force nodes to download needed artifacts directly from internet?

Thank you for taking time to answer.

**Comment by 24sama** [comment]
At present, kk only supports this way to make sure every node have these binaries(e.g. docker). Because of this, kk doesn't need to add additional codes for offline installation. The kk only needs to check if these binaries is existed in the kk's work directory (`./kubekey`) and then scp them to other nodes. Besides, kk uses goroutines to execute scp tasks concurrently.

**Comment by tgruenert** [comment]
Thank you @24sama for your explanation. So for me the main reason to this is not having different code for on/offline installation. This is quite a valid argument for me.

As I wrote, with a medium or small bandwith internet connection for your station you might not able to upload - im my case - 
~375MB * {countOfNodes}. If this is needed, installation should be done from another host or one host of the new cluster. 

But nice to know the "why". Thank you again!
