### ISSUE TITLE
kk install ERROR when use nfs storage 

### ISSUE THREAD

**Issue by hawking-lab** [kubesphere/kubekey#253]
INFO[11:15:11 CST] Deploying storage plugin ...
ERRO[11:15:36 CST] Failed to fetch nfs-client-provisioner chart: Failed to exec command: sudo -E /bin/sh -c "rm -rf /etc/kubernetes/addons/nfs-client-provisioner && /usr/local/bin/helm fetch kubesphere/nfs-client-provisioner -d /etc/kubernetes/addons --untar"
Error: repo kubesphere not found: Process exited with status 1  node=10.124.xx.x

**Comment by pixiake** [comment]
`Error: repo kubesphere not found`
Probably due to the repo was not added successfully.
KubeKey has adjusted how to configure the storage plugin.
https://github.com/kubesphere/kubekey/blob/master/docs/addons.md

You can try to install with the latest release of kubekey.
https://github.com/kubesphere/kubekey/releases/

**Comment by Forest-L** [comment]
Have you resolved your issues, @hawking-lab  ? Please let me know if you have any other questions or close this issue.

**Comment by 24sama** [comment]
I will close this issue. Feel free to reop it.
/close
