### ISSUE TITLE
a suggestion about kubekey with harbor

### ISSUE THREAD

**Issue by bruceforlearn** [kubesphere/kubekey#490]
When kubekey installs the k8s cluster, can you add a harbor option which install the harbor synchronously to distribute the certificate to each node, instead of manually updating daemon.json

thank you

**Comment by LinuxSuRen** [comment]
hi, @bruceforlearn , thanks for your suggestion.

Harbor is an important component for many users. Update the config of docker daemon manually is painful especially there's plenty of them. I also wish that having a command to do it quickly.

But in my opinion, kubekey probably should focus on the installation for Kubernetes and KubeSphere. Some features like the above can be a plugin of kubekey instead of the core part. Of course, there's no plugin mechanism for now. Anyway, it might be good solution to have a plugin mechanism in the future version.

/kind feature-request

**Comment by 24sama** [comment]
https://github.com/kubesphere/kubekey/pull/955 I think this PR can fix this issue. 

Here is a guide for using it: https://github.com/kubesphere/kubekey/blob/master/docs/registry.md

**Comment by 24sama** [comment]
I will close this issue. Feel free to reopen it if you have any questions.
