### ISSUE TITLE
kubekey improve Directory Structure

### ISSUE THREAD

**Issue by shake** [kubesphere/kubekey#819]
### Your current KubeKey version

1.20

### Describe this feature

# tree
.
├── config
│   └── flannel.yaml
├── kk
└── kubekey
    ├── config-sample
    ├── network-plugin.yaml
    └── v1.21.5
        └── amd64
            ├── cni-plugins-linux-amd64-v0.9.1.tgz
            ├── crictl-v1.22.0-linux-amd64.tar.gz
            ├── docker-20.10.8.tgz
            ├── etcd-v3.4.13-linux-amd64.tar.gz
            ├── helm
            ├── kubeadm
            ├── kubectl
            └── kubelet

4 directories, 12 files

the config-sample and network-plugin.yaml , whether can put in folder relate the k8s version.

### Describe the solution you'd like

.
├── kk
└── kubekey
    └── v1.21.5
        ├── amd64
        │   ├── cni-plugins-linux-amd64-v0.9.1.tgz
        │   ├── crictl-v1.22.0-linux-amd64.tar.gz
        │   ├── docker-20.10.8.tgz
        │   ├── etcd-v3.4.13-linux-amd64.tar.gz
        │   ├── helm
        │   ├── kubeadm
        │   ├── kubectl
        │   └── kubelet
        └── config
            ├── config-sample
            ├── flannel.yaml
            └── network-plugin.yaml

like this.

### Additional information

flannel.yaml file was create by kk create.

**Comment by 24sama** [comment]
The content of `config-sample.yaml` depends on the environment that the user wants to customize. Most of the time, `config-sample.yaml` can't be reused for different enviroment, we need to modify its content for different enviroment. For now, i think it's better to manage `config-sample.yaml` explicitly rather than assciate `config-sample.yaml` with kubernetes version. 

If i misunderstand what you mean, feel free to remind and reply me. Thanks!

BTW, we decide to refactor the whole process of air-gapped installtion recently. If you have some ideas or other feature-requests, welcome to present them.
