### ISSUE TITLE
Deploy kubesphere only

### ISSUE THREAD

**Issue by liangyuanpeng** [kubesphere/kubekey#821]
### Your current KubeKey version

version.BuildInfo{Version:"1.2.0", GitCommit:"c3068bf", GitTreeState:"", GoVersion:"go1.16.9"}

### Describe this feature

Deploy kubesphere only from kubekey

### Describe the solution you'd like

Deploy kubesphere only from kubekey

### Additional information

```
[root@node2 kubekey]# kk
Deploy a Kubernetes or KubeSphere cluster efficiently, flexibly and easily. There are three scenarios to use KubeKey.
1. Install Kubernetes only
2. Install Kubernetes and KubeSphere together in one command
3. Install Kubernetes first, then deploy KubeSphere on it using https://github.com/kubesphere/ks-installer
```  

I want to know this `3. Install Kubernetes first, then deploy KubeSphere on it using https://github.com/kubesphere/ks-installer` is say kubekey install kubernetes only?(The first point)  

And i just want to use kubekey deploy kubesphere in existing kubernetes.  Remind me if i missed some doc,thanks.

**Comment by 24sama** [comment]
Hi @liangyuanpeng 
As the help comment says, kk only install kuberentes cluster, and kk can deploy kubesphere because of there are ks-installer(kubesphere deploy tool) deployment yaml files in the kk's code. 

If you want to deploy kubesphere in exsiting kubernetes, you can refer to this [doc](https://github.com/kubesphere/ks-installer#to-start-deploying-kubesphere).

**Comment by liangyuanpeng** [comment]
> 

So kubekey just have two mode, 
1. Install Kubernetes only  
2.  Install Kubernetes and KubeSphere together in one command  

Just confuse third point, kubekey  also install kubernetes only.

**Comment by FeynmanZhou** [comment]
> 

Yes, Kubernetes is neccessary.
